// seed.js — run locally with: node seed.js
// Generates the SQL to seed your D1 database with hashed passwords and recurring goals
// Run: node seed.js > seed_output.sql
// Then: wrangler d1 execute xterra-tracker-db --file=seed_output.sql

const crypto = require('crypto');

async function hashPassword(password) {
  const hash = crypto.createHash('sha256').update(password).digest('base64');
  return hash;
}

const RECURRING = {
  ryan: [
    'Submit weekly operational report to Andrew — structured, solution-oriented, includes front end status and identified issues with proposed resolutions',
    'Active issue log reviewed and updated — all open front end items have current resolution status',
    'Desiree and Lauren direction provided — call center KPIs reviewed, guidance given, no unresolved escalations pending',
    'Scheduling portal reviewed — no unresolved workflow issues or veteran-facing disruptions',
    'Veteran intake pipeline checked — no unresolved bottlenecks delaying veteran progression to consultation',
    'Front end to back end handoff confirmed clean — documented and reported to Andrew',
  ],
  luis: [
    'Submit weekly operational report to Andrew — structured, solution-oriented, includes provider health, letter production, and GHL status',
    'All active providers contacted — weekly check-in completed, no unresolved provider issues outstanding',
    'Letter production throughput tracked — each provider output reviewed against weekly targets (30–40 letters/wk), underperformance flagged',
    'Provider utilization reviewed with Rachel Grade — data current, optimization actions identified or confirmed on track',
    'GHL migration milestone status reported to Andrew — build progress confirmed, blockers surfaced if any',
    'Letter writing portal reviewed — no unresolved provider-facing issues, portal operational integrity confirmed',
  ],
};

async function main() {
  // Default passwords — CHANGE THESE after first login
  const adminHash = await hashPassword('Xterra@Admin2026');
  const ryanHash  = await hashPassword('Xterra@Ryan2026');
  const luisHash  = await hashPassword('Xterra@Luis2026');

  const lines = [];
  lines.push('-- Generated by seed.js');
  lines.push('-- Run: wrangler d1 execute xterra-tracker-db --file=seed_output.sql --remote');
  lines.push('');
  lines.push(`UPDATE users SET password_hash = '${adminHash}' WHERE id = 'usr-admin';`);
  lines.push(`UPDATE users SET password_hash = '${ryanHash}'  WHERE id = 'usr-ryan';`);
  lines.push(`UPDATE users SET password_hash = '${luisHash}'  WHERE id = 'usr-luis';`);
  lines.push('');

  for (const [pid, goals] of Object.entries(RECURRING)) {
    for (let w = 1; w <= 12; w++) {
      goals.forEach((text, i) => {
        const id = `${pid}-w${w}-r${i}`;
        const escaped = text.replace(/'/g, "''");
        lines.push(`INSERT OR IGNORE INTO goals (id, person, week, text, source, status, sort_order) VALUES ('${id}', '${pid}', ${w}, '${escaped}', 'recurring', 'pending', ${i});`);
      });
    }
  }

  console.log(lines.join('\n'));
}

main();
