-- Generated by seed.js
-- Run: wrangler d1 execute xterra-tracker-db --file=seed_output.sql --remote
UPDATE users SET password_hash = 'XZCZs0ZpH4RQKYViMzt/Ejr0znx8l80sKxYBMYpv/7U=' WHERE id = 'usr-admin';
UPDATE users SET password_hash = 'ciZM/ntmKc2x12SQ+X6FgsD8sV9LGCBENpbVnQdi97A='  WHERE id = 'usr-ryan';
UPDATE users SET password_hash = 'Ska25W+BojdhXZqiqluvtThcA/Yi6ofuBEC5lUgYOfs='  WHERE id = 'usr-luis';